sqlite:
  path: "/path/to/your/database.db"

github:
  token: "your_github_token"
  owner: "your_github_owner"
  repo: "your_github_repo"
  configFilePath: "path/to/config/file"
  branch: "main"

user:
  username: "zhangsan"
