name: Scheduled Database Update

on:
  schedule:
    - cron: '0 0 * * *'  # 每天晚上 12 点 UTC，相当于北京时间每天早上 8 点执行
  workflow_dispatch:

jobs:
  update-database:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Copy script to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}             # 服务器 IP 或主机名
        username: ${{ secrets.SERVER_USER }}         # 服务器用户名
        password: ${{ secrets.SERVER_PASSWORD }}     # 服务器密码
        port: ${{ secrets.SERVER_PORT }}             # 端口号
        source: './update_database.sh'               # 脚本路径
        target: '/github_actions'                    # 目标路径
      env:  
        USERNAME: ${{ secrets.USERNAME }}
        OPEN_ID: ${{ secrets.OPEN_ID }}
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}

    - name: Run script on server with retry
      id: run-script
      run: |
        max_attempts=5
        attempt=1
        while [ $attempt -le $max_attempts ]; do
          echo "Attempt $attempt of $max_attempts..."
          if ssh -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} 'bash /github_actions/update_database.sh'; then
            echo "Script executed successfully."
            break
          else
            echo "Script failed. Retrying in 2 minutes..."
            sleep 120  # 等待2分钟
          fi
          attempt=$((attempt + 1))
        done

    - name: Notify on failure
      if: steps.run-script.outcome == 'failure'
      run: |
        echo "The script failed after $max_attempts attempts."
